In [1]:
%run py_import.py

In [2]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index = list('acde'))
s2 = pd.Series([-2.1,-3.6,-1.5,4,3.1], index = list('acefg'))

In [3]:
print(s1)
print('\n')
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64


a   -2.1
c   -3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [4]:
s1 + s2

a    5.2
c   -6.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [5]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [6]:
print(df1)
print('\n')
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0


          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [7]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [8]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [9]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [10]:
df1.add(df2, fill_value = 0)  # 使用fill_value将缺失值替换为0

A    B
0  1.0  3.0
1  2.0  4.0

**DataFrame 和 Series 间的操作**

In [11]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr[0]

array([0, 1, 2, 3])

In [13]:
arr - arr[0]   #广播机制，类似于Numpy

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [14]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3), 
                     index = ['Utah','Ohio','Texas','Oregon'], 
                     columns = list('bde'))
series = frame.iloc[0]    # 行索引

In [15]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [16]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [17]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [20]:
series2 = pd.Series(np.arange(3),index = list('bef'))
series2

b    0
e    1
f    2
dtype: int32

In [19]:
frame + series2   # 如果索引值不在DataFrame的列中，也不在Series的索引中，则对象会重建索引并形成联合

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [23]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [25]:
frame.sub(series3, axis = 'index')   # 在列上计算，在行上匹配

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0