In [1]:
import numpy as np

In [2]:
a = [1, 2 ,3,'4']
a

[1, 2, 3, '4']

In [4]:
# Numpy中的数组的数据类型一定一致
b = np.array([4,5,'6'])
b

array(['4', '5', '6'], dtype='<U11')

In [5]:
# 创建数组的几种方法
# 1. 使用np.array创建数组，把Python列表转换成数组
a1 = np.array([1,2,3,4])
print(a1)
print(type(a1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [7]:
# 2. 使用np.arange生成，类似于range
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [12]:
# 3. np.random 生成随机数组
c = np.random.random((2,3))
c

array([[0.01659327, 0.06351335, 0.66982861],
       [0.32427794, 0.53052588, 0.06956455]])

In [14]:
 d = np.random.randint(0,9,size=(4,4))
d

array([[7, 6, 6, 3],
       [4, 0, 7, 2],
       [3, 5, 0, 7],
       [2, 0, 2, 7]])

In [25]:
# 4. 使用函数生成特殊数组
array_zeros = np.zeros((3,3))
#array_zeros

array_ones = np.ones((4,4))
#array_ones

array_full = np.full((2,2),8)
#array_full

array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])