In [3]:
import numpy as np

In [6]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [7]:
b = np.array([1,2,3,4,5],dtype = np.int8)
print(b)
print(b.dtype)

[1 2 3 4 5]
int8


In [8]:
c = np.array([1,2,3,4,5],dtype = np.float16)
print(c)
print(c.dtype)

[1. 2. 3. 4. 5.]
float16


In [5]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
d = np.array([Person("Bob",18),Person("Hanzo",17)])
print(d)
print(d.dtype)

object


In [9]:
f = np.array(["a","b"],dtype = "S")
print(f)
print(f.dtype)

[b'a' b'b']
|S1


In [10]:
e = np.array(["a","b"],dtype = "U")
print(e)
print(e.dtype)

['a' 'b']
<U1


In [11]:
uf = f.astype('U')
print(uf)
print(uf.dtype)
print(f.dtype)

['a' 'b']
<U1
|S1


# 总结：
1. 为什么Numpy的数组中有很多数据类型？
    * Numpy是C语言便写，C语言本身有很多数据类型，直接引用过来了
    * Numpy为了考虑处理海量数据，针对不同的数据给到不同的数据类型，来节省内存空间，所以有不同的数据类型
2. Numpy的数组的元素有哪些数据类型？
3. 使用ndarray.astype可以修改数组元素的数据类型。