In [2]:
import numpy as np

In [8]:
# 1. 一维数组的索引和切片
a1 = np.arange(10)
#print(a1)

#1.1 索引操作
print(a1[4])

# 1.2 切片操作
print(a1[4:6])

# 1.3 使用步长
print(a1[::2])

# 1.4 使用负数作为索引
print(a1[-1])

4
[4 5]
[0 2 4 6 8]
9


In [9]:
# 2. 多维数组

# 也是通过中括号，在中括号中，用逗号进行分割，逗号前面是行，逗号后面是列
# 如果多维数组中只有一个值，那这个就是行

a2 = np.random.randint(0,10,size = (4,6))
print(a2)

[[6 7 8 9 9 9]
 [1 5 7 6 8 1]
 [6 6 0 7 0 6]
 [3 5 8 2 2 6]]


In [10]:
a2[0]

array([6, 7, 8, 9, 9, 9])

In [11]:
a2[1:3]

array([[1, 5, 7, 6, 8, 1],
       [6, 6, 0, 7, 0, 6]])

In [12]:
a2[[0,2,3]]  # 两个方括号

array([[6, 7, 8, 9, 9, 9],
       [6, 6, 0, 7, 0, 6],
       [3, 5, 8, 2, 2, 6]])

In [16]:
a2[2,2]

0

In [15]:
a2[[1,2],[4,5]]   #获取第1行第4列 和 第2行第5列的数据，从0开始计算

array([8, 6])

In [17]:
a2[1:3,4:6]

array([[8, 1],
       [0, 6]])

In [18]:
a2[:,1]  # 获取列的数据

array([7, 5, 6, 5])

# 总结：
1. 如果索引是一维的，索引和切片和Python中列表一样
2. 如果是多维的，那么中括号中，给两个值，用逗号分开，逗号前面是行，逗号后面是列
3. 如果是多维数组，那么行的部分和列的部分，都是遵循一维数组的方式，可以使用整型、切片，还可以使用中括号的形式来代表不连续的