In [1]:
import numpy as np

In [2]:
v1 = np.random.randint(0,10,size = (3,4))
v1

array([[1, 7, 7, 7],
       [6, 8, 0, 9],
       [9, 7, 2, 8]])

In [3]:
v2 = np.random.randint(0,10,size = (1,4))
v2

array([[7, 6, 9, 3]])

In [8]:
# v3 = np.vstack([v1,v2])
v3 = np.concatenate([v1,v2],axis = 0)
v3

array([[1, 7, 7, 7],
       [6, 8, 0, 9],
       [9, 7, 2, 8],
       [7, 6, 9, 3]])

In [5]:
h1 = np.random.randint(0,10,size = (3,4))
h1

array([[9, 0, 7, 6],
       [7, 6, 0, 5],
       [2, 2, 8, 5]])

In [6]:
h2 = np.random.randint(0,10,size = (3,1))
h2

array([[9],
       [0],
       [5]])

In [9]:
# h3 = np.hstack([h1,h2])
h3 = np.concatenate([h1,h2],axis = 1)
h3

array([[9, 0, 7, 6, 9],
       [7, 6, 0, 5, 0],
       [2, 2, 8, 5, 5]])

In [10]:
h4 = np.concatenate([h1,h2],axis = None)
h4

array([9, 0, 7, 6, 7, 6, 0, 5, 2, 2, 8, 5, 9, 0, 5])

# 总结：
1. hstack代表在水平方向叠加，行必须一致
2. vstack代表在垂直方向叠加，列必须一致
3. concatenate可以手动指定axis参数具体在哪个方向叠加，如果axis = 0，垂直叠加，如果axis = 1，代表水平方向叠加，如果axis = None，则先进行叠加，再转换成一维数组