In [1]:
import numpy as np

In [3]:
hs1 = np.random.randint(0,10,size = (3,4))
hs1

array([[8, 7, 8, 4],
       [0, 7, 0, 8],
       [3, 0, 5, 8]])

In [9]:
np.hsplit(hs1,2)   # 水平方向切割，代表可以分成几列

[array([[8, 7],
        [0, 7],
        [3, 0]]),
 array([[8, 4],
        [0, 8],
        [5, 8]])]

In [7]:
np.hsplit(hs1,(1,2))

[array([[8],
        [0],
        [3]]),
 array([[7],
        [7],
        [0]]),
 array([[8, 4],
        [0, 8],
        [5, 8]])]

In [10]:
vs1 = np.random.randint(0,10,size = (4,5)) # 垂直方向切割，代表可以分成几行
vs1

array([[9, 9, 6, 1, 8],
       [4, 6, 5, 6, 3],
       [8, 2, 3, 6, 8],
       [6, 2, 2, 4, 4]])

In [11]:
np.vsplit(vs1,4)

[array([[9, 9, 6, 1, 8]]),
 array([[4, 6, 5, 6, 3]]),
 array([[8, 2, 3, 6, 8]]),
 array([[6, 2, 2, 4, 4]])]

In [12]:
np.vsplit(vs1,(1,3))

[array([[9, 9, 6, 1, 8]]),
 array([[4, 6, 5, 6, 3],
        [8, 2, 3, 6, 8]]),
 array([[6, 2, 2, 4, 4]])]

In [15]:
np.split(hs1,4,axis = 1)

[array([[8],
        [0],
        [3]]),
 array([[7],
        [7],
        [0]]),
 array([[8],
        [0],
        [5]]),
 array([[4],
        [8],
        [8]])]

In [16]:
np.split(vs1,4,axis = 0)

[array([[9, 9, 6, 1, 8]]),
 array([[4, 6, 5, 6, 3]]),
 array([[8, 2, 3, 6, 8]]),
 array([[6, 2, 2, 4, 4]])]

# 总结：
1. hsplit水平方向切割，代表可以分成几列，切割方式有两种，第一种是直接指定平均分成多少列，第二种是指定切割的下标
2. vsplit垂直方向切割，代表可以分成几行，切割方式同上
3. split是手动指定axis参数切割，axis = 0代表按照行切割，axis = 1代表按照列切割