In [1]:
import numpy as np

In [2]:
# 不拷贝
a = np.arange(12)
b = a
print( b is a)

True


In [4]:
# 浅拷贝
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
c = a.view()
print(c is a)
c[0] = 100
a

False


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [9]:
# 深拷贝
a
d = a.copy()
print(d is a)
d[1] = 200
a

False


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [10]:
a1 = np.random.rand(2,4)
a1

array([[0.23198833, 0.05369761, 0.82180197, 0.78810328],
       [0.32233023, 0.79577054, 0.35304672, 0.77978247]])

In [11]:
a2 = a1.ravel()
a2[0] = 0
a1  #修改了a1的值，说明ravel返回的是一个浅拷贝

array([[0.        , 0.05369761, 0.82180197, 0.78810328],
       [0.32233023, 0.79577054, 0.35304672, 0.77978247]])

In [12]:
a3 = a1.flatten()
a3[1] = 1
a3  # flatten返回的是一个深拷贝

array([0.        , 1.        , 0.82180197, 0.78810328, 0.32233023,
       0.79577054, 0.35304672, 0.77978247])

# 总结：
在数组操作中分成3种拷贝：
1. 不拷贝：直接赋值，栈区没有拷贝，只是同一个栈区定义了不同的名称
2. 浅拷贝：只拷贝栈区，指定的堆区没有拷贝
3. 深拷贝：栈区和堆区都拷贝