In [1]:
import numpy as np

In [3]:
# 文件保存
scores = np.random.randint(0,100, size = (20, 2))
scores

array([[66, 70],
       [48,  5],
       [60, 60],
       [63, 83],
       [95,  5],
       [ 8, 43],
       [54, 73],
       [61, 63],
       [18, 20],
       [75, 72],
       [84, 87],
       [ 6,  1],
       [49, 51],
       [88,  1],
       [97, 93],
       [81, 73],
       [75, 12],
       [71, 94],
       [27, 50],
       [59, 46]])

In [10]:
np.savetxt('scores.csv', scores, delimiter = ',', header = '英语,数学',comments = '',fmt = '%d')

In [12]:
# 读取文件
b = np.loadtxt('scores.csv',dtype = np.int32,delimiter = ',', skiprows = 1)
b

array([[66, 70],
       [48,  5],
       [60, 60],
       [63, 83],
       [95,  5],
       [ 8, 43],
       [54, 73],
       [61, 63],
       [18, 20],
       [75, 72],
       [84, 87],
       [ 6,  1],
       [49, 51],
       [88,  1],
       [97, 93],
       [81, 73],
       [75, 12],
       [71, 94],
       [27, 50],
       [59, 46]])

In [14]:
# Numpy独有存储方法
c  = np.random.randint(0, 10, size = (2,3))
np.save('c', c)

In [15]:
c1 = np.load('c.npy')b
c1

array([[0, 6, 4],
       [0, 1, 3]])

In [16]:
d = np.random.randint(0,10, size = (2,3,4))   #savetxt只能存储一维或者二维数组
np.save('d',d)

# 总结：
1. np.savetxt和np.loadtxt一般用来操作csv文件，可以设置header，但是不能存储三维以上数组
2. np.save和np.load一般用来存储非文本类型的文件，不可以设置header，但是能存储三维以上数组
3. 如果想专门操作csv文件，有一个模块叫做csv，Python内置